Repository furukawa-laboratory/workout_report_2019, pull requests merged in 2019-04, with the labels that each got.

#2 #1 Finish README.md
  README.md
  menu/README.md
Labels: prepare

#5 Update README.md
  README.md
  menu/README.md
Labels: prepare

#8 Tweak README.md
  README.md
Labels: prepare

#11 Rename .gihub .github
  .github/ISSUE_TEMPLATE/Issue_template.md
Labels: prepare

#12 Create trainees' folders, tweak README.md
  README.md
  menu/README.md
  trainee/README.md
  trainee/harada/README.md
  trainee/noguchi/README.md
  trainee/takano/README.md
  trainee/tsuno/README.md
Labels: prepare

#23 first commit by tsuno
  trainee/tsuno/README.md
Labels: training

#24 1st commit.
  trainee/yamauchi/README.md
Labels: training

#15 Update README.md
  README.md
  menu/README.md
Labels: prepare

#26 Read meを変更しました
  trainee/takano/README.md
Labels: training

#27 Update README.md
  trainee/harada/README.md
Labels: training

#17 Add description in the menu
  menu/README.md
Labels: prepare

#25 #22の解決（トレーニング）
  trainee/noguchi/README.md
Labels: training

#47 edit link in menu.README.md
  menu/README.md
Labels: bug, prepare

#45 前処理でのつまずきポイント
  .ipynb_checkpoints/preprocessing-checkpoint.ipynb
  trainer/hatano/preprocessing.ipynb
  trainer/hatano/preprocessing.py
Labels: description

#53 Update README.md
  README.md
Labels: description

#41 #30_Introduction_of_Preprocessing_01
  .gitignore
  trainee/yamauchi/Introduction_of_Preprocessing_01.ipynb
Labels: training
